#!/usr/bin/python3
import os
import zipfile
import urllib.request
import urllib.parse
import json
import re
from shutil import copy

request = urllib.request.Request("https://api.github.com/repos/validator/validator/releases/latest");
token = os.getenv("AUTH_TOKEN");
if token:
	request.add_header("Authorization", "token " + token);
with urllib.request.urlopen(request) as url:
	assets = json.loads(url.read().decode())["assets"];
	for asset in assets:
		if re.match("^vnu\\.jar.*zip$", asset["name"]):
			with urllib.request.urlopen(asset["browser_download_url"]) as response:
				filename = "vnu.zip";
				with open(filename, "wb+") as out_file:
					data = response.read();
					out_file.write(data);
					with zipfile.ZipFile(filename,"r") as file:
						file.extractall();
						copy("./dist/vnu.jar", "./");
			break;
