#!/usr/bin/python3
import zipfile
import urllib.request
import json
import re
from shutil import copy

with urllib.request.urlopen("https://api.github.com/repos/validator/validator/releases/latest") as url:
	assets = json.loads(url.read().decode())["assets"];
	for asset in assets:
		if re.match("^vnu\\.jar.*zip$", asset["name"]):
			with urllib.request.urlopen(asset["browser_download_url"]) as response:
				filename = "vnu.zip";
				with open(filename, "wb+") as out_file:
					data = response.read();
					out_file.write(data);
					with zipfile.ZipFile(filename,"r") as file:
						file.extractall();
						copy("./dist/vnu.jar", "./");
			break;
