#!/bin/bash
set -e
mkdir ./.binary/
cd ./.binary/

VALIDATOR_VERSION=17.9.0
VALIDATOR_TMP_ZIP=$(mktemp --suffix=.zip)
wget \
  -O "$VALIDATOR_TMP_ZIP" \
  "https://github.com/validator/validator/releases/download/$VALIDATOR_VERSION/vnu.jar_$VALIDATOR_VERSION.zip"
unzip -j "$VALIDATOR_TMP_ZIP" dist/vnu.jar
rm "$VALIDATOR_TMP_ZIP"

git clone https://github.com/w3c/css-validator.git
cd ./css-validator/
git checkout 83d7505d36887dfc5edc0cdce2cfc038f3bb5807
ant jar -q
cd ..
git clone https://github.com/RoiEXLab/link-checker.git
cd ./link-checker/
./gradlew jar -q
cd ../../
